FlowCrypt/flowcrypt-android

- README.md
`https://developer.android.com/training /testing` -> https://developer.android.com/training/testing
I assume this is what it's meant to be :)
> Accidental space breaks URL

- .gitignore
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/util/gson/MsgBlockAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/IncomingMessageInfo.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/node/gson/MsgBlockDeserializer.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/node/GenericMsgBlock.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/node/MsgBlock.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/node/MsgBlockFactory.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/node/ParseDecryptedMsgResult.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/MsgBlockParser.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/CryptoArmorHeaderDefinition.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpArmor.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/ParcelableTest.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/core/msg/MsgBlockParserTest.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/jfixture/MsgBlockTypeRelay.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpPwdTest.kt
> issue #1052 port MsgBlockParser from TypeScript to Kotlin

- .idea/.gitignore
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/enterprise/AddNewAccountActivityEnterpriseTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/enterprise/SignInActivityEnterpriseTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/api/LoginResponse.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/EnterpriseDomainRulesViewModel.kt
- FlowCrypt/src/main/res/values/strings.xml
Not sure if this is completely correct. See my comment in the #868.  Now just want to see if semaphore passes.
> issue #868 dismiss registered field

- .idea/.gitignore
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ImportPrivateKeyActivityFromSettingsTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/node/NodeKeyDetails.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/pgp/PGPKeyRingExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/LoadPrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/SecurityUtils.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpKey.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/CheckClipboardToFindKeyService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/actionqueue/actions/BackupPrivateKeyToInboxAction.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/actionqueue/actions/EncryptPrivateKeysIfNeededAction.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PreviewImportPgpContactFragment.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt
> issue #1098 encrypt and decrypt private keys with PGPainless

- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpKey.kt
This PR refactors `PgpKey` class. Modified `PgpKey.extractSecretKeyRing` to use `PGPainless` realization for the key parsing.
I'm not sure that those changes fix #1157, but after them, the issue will not contain a valid `stacktrace`. And I'd like to drop an own realization for the key parsing. It'll be better to use `PGPainless` for that and fix errors there.
close #1157 // if this PR closes an issue
> Modified PgpKey.| #1157

- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpDecrypt.kt
This PR refactored code to use PGPainless/WrongPassphraseException instead of the own realization
close #1237
> Refactored code to use PGPainless/WrongPassphraseException 

- .github/workflows/check-for-emails.yml
This PR exempts certain domains from email monitoring in comments (per @DenBond7  feedback in https://github.com/FlowCrypt/flowcrypt-android/issues/1238). It also changes the name of the action from main.yml (per @Limonte's feedback in https://github.com/FlowCrypt/flowcrypt-browser/pull/3645)
As is, this exempts addresses that end in 'test' and 'example.com', but that can be modified however we like, so just let me know.
close https://github.com/FlowCrypt/flowcrypt-security/issues/128
> add exempt domains to gh action

- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/bouncycastle/openpgp/PGPKeyRingExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/model/PgpKeyDetails.kt
This PR made PgpKeyDetails.lastModified as nullable to prevent NPE
close #1260 // if this PR closes an issue
> Made PgpKeyDetails.lastModified as nullable. Refactored code.| #1260

- FlowCrypt/build.gradle
- FlowCrypt/src/main/java/com/flowcrypt/email/api/wkd/WkdClient.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/kotlin/StringExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/BetterEmailAddress.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/api/email/WkdClientTest.kt
This PR adds WKD client class with logic ported from Typescript
close #1317
> issue #1317 WKD client

- FlowCrypt/build.gradle
- ext.gradle
This PR added migration to Java 11
close #1376 
> Migrated to use Java 11 as a default JDK.| #1376

- FlowCrypt/build.gradle
- FlowCrypt/src/main/java/com/flowcrypt/email/api/wkd/WkdClient.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/kotlin/StringExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/BetterEmailAddress.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/api/email/WkdClientTest.kt
This PR adds timeout test for the WKD client and introduces few small fixes to the WKD client itself 
close #1378
related issue #1317
> issue #1378 WKD client timeout test

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ImportPgpContactActivityDisallowAttesterSearchForDomainTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ImportPgpContactActivityDisallowAttesterSearchTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/base/BaseCreateMessageActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragmentDisallowAttesterSearchForDomainTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragmentDisallowAttesterSearchTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/ApiRepository.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/FlowcryptApiRepository.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/OrgRules.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/AccountKeysInfoViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ContactsViewModel.kt
This PR added handling disallow_attester_search_for_domains OrgRule
close #1203
> Added handling disallow_attester_search_for_domains OrgRule

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/MsgsCacheManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt
This PR fixed "message not found in the local cache" issue.
close #1549
> Fix "message not found in the local cache" issue

- FlowCrypt/schemas/com.flowcrypt.email.database.FlowCryptRoomDatabase/28.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/database/MigrationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/AttachmentInfo.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/AttachmentEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/ForwardedAttachmentsDownloaderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/MessagesSenderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/SecurityUtils.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpDecryptAndOrVerify.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpEncryptAndOrSign.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/PrepareOutgoingMessagesJobIntentService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/AttachmentsRecyclerViewAdapter.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpDecryptAndOrVerifyTest.kt
This PR added the ability to forward any attachments.
It means we can forward an encrypted message with detached attachments as an encrypted message(in that case we will download, decrypt and encrypt attachments with new pub keys before sending) or as a standard message(in that case we will download and decrypt attachments before sending)
close #1538
- Difficult to test (explain why): It relates to flow testing that we don't support yet. Tested manually.
>  ability to forward detached encrypted attachments(no inline)

- FlowCrypt/schemas/com.flowcrypt.email.database.FlowCryptRoomDatabase/30.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/database/MigrationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/CreateMessageActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/CreateMessageFragmentPasswordProtectedTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/AccountEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
This PR disabled password-protected messages for accounts if FES is not used
close #1621
> Disabled password-protected messages for accounts if FES is not used

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt
This PR Added a retry strategy to get `idToken`
close #1614
- Difficult to test (explain why): It relates to testing Google Services. Don't know how to test. Also, the token expires every hour. To test need to wait at least one hour. Tested manually.
> Added a retry strategy to get idToken.| #1614

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ImportRecipientAllowAttesterSearchOnlyForDomainsEmptyFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ImportRecipientAllowAttesterSearchOnlyForDomainsFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/ApiRepository.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/FlowcryptApiRepository.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/OrgRules.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/AccountPublicKeyServersViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/RecipientsViewModel.kt
This PR added an ability to allow attester search only for domains
close #1827
> Added an ability to allow attester search only for domains.| #1827

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
This PR Fixed depreaction for onRequestPermissionsResults
close #1849
> Fixed depreaction for onRequestPermissionsResults.| #1849

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/RefreshKeysFromEkmFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/RefreshRevokedKeysFromEkmDeleteNotMatchingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/RefreshRevokedKeysFromEkmFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseRefreshKeysFromEkmFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/RefreshPrivateKeysFromEkmViewModel.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/api/email/WkdClientTest.kt
This PR improved revoked handing
close #1768
> EKM keys refresh: allow removing keys + improve revoked handing

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
This PR Fixed visibility of btnSetWebPortalPassword when we use a standard mode
close #1928
- Difficult to test (explain why). Updating recipients is an async operation. For such a case we use Espresso idling, it waits while the async operation will be completed. But to test this issue we have to switch to the "Encrypted mode" while the app updates recipients. Anyway, it was tested manually.
> Issue 1928 fix visibility of btnsetwebportalpassword

- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
This PR Fixed deprecation for GeneralUtil.isConnected()
close #1943
> Fixed deprecation for GeneralUtil.isConnected().| #1943

- FlowCrypt/src/main/AndroidManifest.xml
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/NotificationsSettingsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/SecuritySettingsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/UIUtil.kt
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR added support of Notification runtime permission for Android 13 (API level 33) and high
close #2021
- Tests will be added later (issue #2022)
> Issue 2021 notification runtime permission

- .semaphore/semaphore.yml
- script/ci-setup-and-run-emulator.sh
- script/ci-wait-for-emulator.sh
This PR fixed resolving `fes.localhost` by Android Emulator on `Semaphore CI`.
close #2155
> Issue 2155 semaphore ci fix dns for localhost

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/DraftsGmailAPITestCorrectDeletingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MainSignInFragmentEnterpriseFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseDraftsGmailAPIFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fes/login/MainSignInFragmentEnterpriseTestUseFesUrlFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
This PR added more tests for FES login
close #2147 
These changes include the following
1. Was added a case where we test that the app calls `FES` server if `FES URL` was provided. It resolves an issue discovered here https://github.com/FlowCrypt/flowcrypt-android/pull/2143#discussion_r1067109242
2. Was added a case where we test that the app uses a regular flow for public domains(`google.com`, `googlemail.com`)
3. I've relooked over the existing tests. They work well.
4. Code refactoring
> more tests for FES login

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/NoPgpFoundDialogFragment.kt
- FlowCrypt/src/main/res/navigation/create_msg_graph.xml
This PR Enabled password protected functionality for everybody
close #2177
> Enabled password protected functionality for everybody.| #2177

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/javamail/PasswordProtectedAttachmentInfoDataSource.kt
This PR Improved PasswordProtectedAttachmentInfoDataSource to use a stream directly instead of reading all data to a buffer.
close #2202
> Improved PasswordProtectedAttachmentInfoDataSource

- FlowCrypt/schemas/com.flowcrypt.email.database.FlowCryptRoomDatabase/37.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/database/MigrationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/KeyEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/RefreshPrivateKeysFromEkmViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/model/PgpKeyDetails.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/actionqueue/actions/EncryptPrivateKeysIfNeededAction.kt
This PR Removed public key field from the 'keys' table as redundant
close #1766
> Removed public key field from the 'keys' table as redundant

- FlowCrypt/build.gradle
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/OutgoingMessageInfo.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/kotlin/IterableExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpEncryptAndOrSign.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/ProcessingOutgoingMessageInfoHelper.kt
This PR fixed issue `hide key ids when sending email with bcc recipients`
close #2306
> hide key ids when sending email with bcc recipients

- FlowCrypt/src/main/res/layout/activity_create_message.xml
- FlowCrypt/src/main/res/layout/activity_main.xml
This PR Fixed Tapjacking for Full occlusion
close #2441
- Difficult to test (explain why). It requires a separate app with Tapjacking funtionality. Tested manually.
> Fixed Tapjacking for Full occlusion

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsGmailAPIArchiveFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseGmailLabelsFlowTest.kt
This PR added a few tests to check the visibility of `Archive` and `Move to Inbox` items in the `Action Bar`
close #2470
> Added MessageDetailsGmailAPIArchiveFlowTest

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/UpdatePrivateKeyWithPassPhraseInDatabaseFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/UpdatePrivateKeyWithPassPhraseInRamFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PrivateKeyDetailsFragmentExpiredKeyInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PrivateKeyDetailsFragmentInIsolationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeyDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PrivateKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PrivateToPublicKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PublicKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BasePublicKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/RecipientsRecyclerViewAdapter.kt
- FlowCrypt/src/main/res/drawable/baseline_content_copy_48.xml
- FlowCrypt/src/main/res/drawable/baseline_save_48.xml
- FlowCrypt/src/main/res/drawable/outline_info_48.xml
- FlowCrypt/src/main/res/layout/fragment_private_key_details.xml
- FlowCrypt/src/main/res/menu/fragment_pub_key_details.xml
- FlowCrypt/src/main/res/navigation/nav_graph.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/dimens.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR Improved the private key details screen UI
close #2506
before 
after
Click on 
opens public keys details screen where a user can see more details
> Improved the private key details screen UI

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/DownloadAttachmentViewModel.kt
This PR Fixed App crashing when try to preview an encrypted attachment
close #2596
- Difficult to test. Success means after clicking on the 'preview' button the app moves a user to another app that can handle the downloaded attachment. But Espresso can work only with its app. Tested manually.
> Fixed App crashing when try to preview an encrypted attachment

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenNoKeyAvailableCreateNewKeyFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenNoKeyAvailableSingleKeyWithPassphraseInDatabaseFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseComposeScreenNoKeyAvailableTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedWithAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/LifecycleOwnerExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/BaseActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/CreateMessageActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateOrImportPrivateKeyDuringSetupFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/ActionsDialogFragment.kt
- FlowCrypt/src/main/res/drawable/ic_create_new_key.xml
- FlowCrypt/src/main/res/navigation/actions_dialog_graph.xml
- FlowCrypt/src/main/res/navigation/create_msg_graph.xml
- FlowCrypt/src/main/res/navigation/create_new_private_key_graph.xml
- FlowCrypt/src/main/res/navigation/nav_graph.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR Handled the case "no private key available for account(create a new key for email)
issue #597
> Handled the case "no private key available for account(create a new key for email)

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/PrivateKeyDetailsFragmentPassInRamFlexibleTimeFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
This PR fixed "Unable to start service com.flowcrypt.email.service.PassPhrasesInRAMService"
close #2703
> fixed "Unable to start service com.flowcrypt.email.service.PassPhrasesInRAMService"

- FlowCrypt/src/main/AndroidManifest.xml
This PR Removed android.permission.RECEIVE_BOOT_COMPLETED
close #2711
> Removed android.permission.RECEIVE_BOOT_COMPLETED as not used by the app directly

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseComposeGmailFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/passwordprotected/BaseComposeScreenPasswordProtectedDisallowedTermsTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/passwordprotected/ComposeScreenPasswordProtectedDisallowedTermsErrorTextMissingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/passwordprotected/ComposeScreenPasswordProtectedDisallowedTermsFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/passwordprotected/ComposeScreenPasswordProtectedDisallowedTermsMissingTermsFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/passwordprotected/ComposeScreenPasswordProtectedDisallowedTermsNullFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/ClientConfiguration.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/api/retrofit/response/model/ClientConfigurationTest.kt
This PR added changes where we check the subjects of composed password-protected email messages for specified strings
close #2905
> Issue 2905 password ptorected message compliance

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/passwordprotected/BaseComposeScreenPasswordProtectedDisallowedTermsTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/passwordprotected/ComposeScreenPasswordProtectedDisallowedTermsFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/ClientConfiguration.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/api/retrofit/response/model/ClientConfigurationTest.kt
This PR Improved Password-protected messages compliance
close #2909 
> Improve Password-protected messages compliance

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/AttachmentDownloadingWithRestrictionFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AddOtherAccountFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ServerSettingsFragment.kt
- build.gradle.kts
- ext.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
This PR Updated project to use SDK 35
close #2912 
> Update project to use SDK 35

- FlowCrypt/build.gradle.kts
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/SendFeedbackHasAccountFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseFeedbackFragmentTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/RetrofitApiServiceInterface.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/SendFeedbackViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/FeedbackFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/SendFeedbackDialogFragment.kt
This PR Migrated to use 'shared-tenant-fes/api/v1/account/feedback' + fixed one small UI bug
close #2827
> Migrated to use 'shared-tenant-fes/api/v1/account/feedback'

- FlowCrypt/build.gradle.kts
- FlowCrypt/src/main/AndroidManifest.xml
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/Context.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/android/webkit/WebViewExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ThreadDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BaseFragment.kt
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
- FlowCrypt/src/main/res/xml/filepaths.xml
- FlowCrypt/src/test/java/com/flowcrypt/email/ParcelableTest.kt
- ext.gradle.kts
This PR added migration to minSdkVersion = Android 10 (API level 29)
close #2941
> minSdkVersion = Android 10 (API level 29)

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
This PR Disabled logging for Gmail API by default(reverted back missed changes)
close #2931
> Disabled logging for Gmail API by default

- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/MessagesInThreadListAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/widget/EmailWebView.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt
This PR fixed "quoted email" issue for standard messages
issue #2902
> Hide the quoted email when display a reply

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/MainSettingsFragmentEnterpriseFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/providers/EmbeddedAttachmentsProvider.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSettingsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ThreadDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/GeneralSettingsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/AttachmentsRecyclerViewAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/MessagesInThreadListAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/FileAndDirectoryUtils.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
- FlowCrypt/src/main/res/drawable/bg_att.xml
- FlowCrypt/src/main/res/drawable/bg_att_decrypted.xml
- FlowCrypt/src/main/res/navigation/nav_graph.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/preferences.xml
- FlowCrypt/src/main/res/values/strings.xml
- FlowCrypt/src/main/res/xml/preferences_general_settings.xml
- FlowCrypt/src/main/res/xml/preferences_main_settings.xml
This PR improved handling attachments. 
1. Added the ability to use any app to preview attachments for users who have a problem with a common approach.
Doesn't affect users with existing `RESTRICT_ANDROID_ATTACHMENT_HANDLING` policy.
https://github.com/user-attachments/assets/450c984d-1e47-4700-b5cb-eaae69147fff
Added a test to cover the following case: Test visibility for `Settings -> General` when `RESTRICT_ANDROID_ATTACHMENT_HANDLING` is present and vice versa.
As intents are handled by the system, it's hard to test 'smart mode' via Espresso(outside of the app scope). Tested manually.
2. Fixed the issue with a wrong name for duplicated downloads.
close #2894
close #2944 …
> improve handling attachments

- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/google/api/services/gmail/model/MessageExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/google/api/services/gmail/model/ThreadExt.kt
This PR Fixed the empty recipients issue(small internal changes)
close #2955
> Fixed empty recipients issue

- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/google/api/services/gmail/model/ThreadExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt
This PR fixed quotes for the plain text version + refactoring for #2957
close #2961
1. Use a web client to create a conversation
2. Create a message via `recipientA`
3. Use `Plain` mode (not `HTML`) and send a message to `recipientB`
4. Open a message via `recipientB` and reply via `Plain` mode
5.  Open a message via `recipientA` and check quotes
- Tests added or updated (Added only JUnit test. UI test is impossible as we can't get `HTML` from `WebView` via `Espresso`).
> quotes for the plain text version + refactoring for #2957

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/passwordprotected/ComposeScreenPasswordProtectedDisallowedTermsReFetchConfigurationFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
This PR added Re-fetch client configuration before sending password-protected messages
close #2975
> Re-fetch client configuration before sending password-protected messages

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseGmailApiTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/ThreadDetailsGmailApiFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/ThreadsListGmailApiFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailHistoryHandler.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/google/api/services/gmail/model/MessageExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/google/api/services/gmail/model/ThreadExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MessagesViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ProcessMessageViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ThreadDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ThreadDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/ProcessMessageDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/exception/MessageNotFoundException.kt
- FlowCrypt/src/main/res/navigation/process_message_dialog_graph.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR fixed issue with displaying deleted messages in a conversation + code refactoring for #2978
close #2973 
> Don't show deleted messages in a conversation

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/LocalFolder.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/MessageEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/google/api/services/gmail/model/MessageExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/DraftViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MessagesViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ProcessMessageViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ThreadDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/BaseIdleWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
This PR Improved drafts functionality
close #2979 
> Improved drafts functionality

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailHistoryHandler.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/SyncDraftsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/MessagesNotificationManager.kt
This PR Fixed a case when Notifications keep coming even after settings option to load "Encrypted only" messages
close #2996
- Difficult to test (explain why): this scenario can be tested when the app is in the background and threads syncing runs once per 15 minutes. It is hard(maybe not possible) to create a UI test using Espresso. Tested manually.
> Fixed a case when Notifications keep coming even after settings option to load "Encrypted only" messages

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailHistoryHandler.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/LocalFolder.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ThreadDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
This PR Fixed opening messages in 'All Mail' folder + fix sync in 'All Mail' folder
close #2995 
> Fixed opening messages in 'All Mail' folder + fix sync in 'All Mail' folder

- FlowCrypt/build.gradle.kts
- script/prod-release.sh
This PR Removed unused code in build.gradle.kts. Added 'checkReleaseBuildsSize' task.
close #3011 
> Removed unused code in build.gradle.kts. Added 'checkReleaseBuildsSize' task.

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/google/api/services/gmail/model/MessageExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/google/api/services/gmail/model/ThreadExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ThreadDetailsViewModel.kt
This PR fixed NPE for Gmail API
close #2998 
> fix NPE for Gmail API

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/base/BaseTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/DraftsGmailAPITestCorrectCreatingAndUpdatingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/DraftsGmailAPITestCorrectDeletingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/DraftsGmailAPITestCorrectSendingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseDraftsGmailAPIFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseGmailApiTest.kt
This PR Fixed some tests for Drafts
close #3026
> Fixed some tests for Drafts

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/AttachmentDownloadingWithRestrictionFlowTest.kt
This PR Enabled AttachmentDownloadingWithRestrictionFlowTest. 
AttachmentDownloadingWithRestrictionFlowTest passes
```
@RunWith(RepeatableAndroidJUnit4ClassRunner::class)
@RepeatableAndroidJUnit4ClassRunner.RepeatTest(50)
```
And looks like it is not flaky now. I've enabled it.
close #3036
> Enabled AttachmentDownloadingWithRestrictionFlowTest.| #3036

- FlowCrypt/src/main/java/com/flowcrypt/email/service/PassPhrasesInRAMService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/BaseActivity.kt
This PR improved running PassPhrasesInRAMService
close #2703 
> Improved running PassPhrasesInRAMService

- .github/CODEOWNERS
This PR Modified CODEOWNERS
ref 
- https://stackoverflow.com/questions/75531641/exclude-codeowners-from-dependabot-pr
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
close #3042
> Modified CODEOWNERS
