FlowCrypt/flowcrypt-android

- .semaphore/semaphore.yml
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/rules/CustomScreenCaptureProcessor.kt
- script/ci-instrumentation-tests-with-mailserver.sh
- script/ci-instrumentation-tests-without-mailserver.sh
- script/ci-junit-tests.sh
- script/ci-lint-checks.sh
- script/ci-wait-for-emulator.sh
it relates to #1078 
1. Fixed publishing failed tests screenshots 
2. Fixed ci-wait-for-emulator.sh
3. Fixed the log formatting
> Improved semaphore settings

- .semaphore/semaphore.yml
- FlowCrypt/build.gradle
Improved stability of running tests on CI
> Issue 1116 fix device offline

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/BackupKeysActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/CreateMessageActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ImportPrivateKeyActivityFromSettingsTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ImportPublicKeyActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ShareIntentsTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/util/TestGeneralUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/CreateMessageFragment.kt
- docker-mailserver/Dockerfile
- docker-mailserver/env-mailserver
This PR increases the max allowed limit of attachments that can be sent
close #1099
**Tests**
> Issue 1099 allow encrypting files up to 25mb

- FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/MessagesSenderWorker.kt
- script/ci-install-android-sdk.sh
- script/ci-setup-and-run-emulator.sh
This PR improved sending messages via Gmail API. From now we are not affected by any message size due to using streams.
close #140
**Tests**:
- Difficult to test (explain why): Due to the Gmail usage.
> Migrated to use messages.upload instead of messages.send| Close #140

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/pgpainless/key/OpenPgpV4FingerprintExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/pgp/PGPKeyRingExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/ForwardedAttachmentsDownloaderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/model/KeysStorage.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/KeysStorageImpl.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/SecurityUtils.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpEncrypt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/PrepareOutgoingMessagesJobIntentService.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpEncryptTest.kt
This PR added an opportunity to always sign outgoing encrypted messages
close #1095 // if this PR closes an issue
- Does not need tests (tested in PGPalinless lib)
> Issue 1095 always sign outgoing encrypted messages

- FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/MsgBlockParser.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/core/msg/MsgBlockParserTest.kt
- script/ci-install-android-sdk.sh
- script/ci-setup-and-run-emulator.sh
This PR fixes StringIndexOutOfBoundsException
close #1154
> Fix StringIndexOutOfBoundsException

- FlowCrypt/build.gradle
- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/acra/CustomReportSender.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/acra/CustomReportSenderFactory.kt
This PR updated ACRA to the latest release version.
close #1164 // if this PR closes an issue
> Updated ACRA to 5.7.0| #1164

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/KeysSettingsActivityTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/FragmentExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/CheckPrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/CheckKeysActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PrivateKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/exception/WrongPassPhraseException.kt
- FlowCrypt/src/main/res/layout/fragment_private_key_details.xml
- FlowCrypt/src/main/res/values/strings.xml
- script/ci-setup-and-run-emulator.sh
This PR added debugging info to identify if the saved passphrase can decrypt a key
issue #1167
> Issue 1167 add verifying passphrase

- .semaphore/semaphore.yml
This PR fixed running robolectric tests on CI
close #1136 // if this PR closes an issue
> Fixed running Robolectric tests.| #1136

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ContactsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PublicKeyDetailsFragment.kt
- FlowCrypt/src/main/res/layout/fragment_public_key_details.xml
This PR removed all things that relate to `keywords` usage
close #1081 // if this PR closes an issue
> Refactored code to remove keywords | #1081

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ImportPgpContactActivityTest.kt
- FlowCrypt/src/androidTest/resources/2.txt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/ImportPgpContactActivity.kt
- FlowCrypt/src/main/res/drawable/ic_person_search_green_24dp.xml
- FlowCrypt/src/main/res/layout/activity_import_public_keys.xml
This PR made the process of searching pub keys by email/fingerprint a little simpler.
close #470 // if this PR closes an issue
> Issue 470 fix search button

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/base/BaseTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/AddOtherAccountFragmentTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/CreatePrivateKeyActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/EmailManagerActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/util/AccountDaoManager.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/util/AuthCredentialsManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/CheckEmailSettingsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AddOtherAccountFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AuthorizeAndSearchBackupsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
- FlowCrypt/src/main/res/values/strings.xml
This PR added a few UI tests
close #1199 // if this PR closes an issue
> Issue 1199 test adding new account

- .github/dependabot.yml
This PR changed dependabot.yml
close #1207
> Modified dependabot.yml.| #1207

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/MessageDetailsActivityPassphraseInRamTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/KeysStorageImpl.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/SecurityUtils.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentNotificationManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/exception/DecryptionException.kt
- FlowCrypt/src/main/res/values/strings.xml
This PR added handling passphrase in RAM when a user is trying to download and decrypt an encrypted attachment
close #1255
> Issue 1255 pass in ram decrypt atts

- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpDecrypt.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpDecryptTest.kt
This PR improved handling DecryptionErrorType.KEY_MISMATCH
close #1238
> Improve handling DecryptionErrorType.KEY_MISMATCH. Added tests.| #1238

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/EmailManagerActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/SecuritySettingsFragmentTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/StandardReplyWithServiceInfoAndOneFileTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/FragmentExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BaseFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/SecuritySettingsFragment.kt
This PR added handling missing passphrases in RAM when a user is trying to change a passphrase
close #1254
> Pass phrase in memory. Change passphrase of imported keys

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/CreateMessageActivityTestTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/ImportPublicKeyActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/widget/CustomChipSpanChipCreator.kt
This PR fixed import pub key for contact
close #1304
> Issue 1304 fix import pub key for contact

- .semaphore/semaphore.yml
This PR added auto-cancel previous ci builds if new commit pushed to branch
close #1299// if this PR closes an issue
> Added auto-cancel previous ci builds if new commit pushed to branch

- FlowCrypt/build.gradle
- ext.gradle
This PR udpated libs
close #1374
> Issue 1374 update libs

- FlowCrypt/src/main/res/layout/activity_check_keys.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR changed some strings
close #1330
> Changed some strings.| #1330

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/IncomingMessageInfo.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/CreateMessageFragment.kt
This PR fixed some issues on the compose screen.
close #1392 // if this PR closes an issue
close #1393 // if this PR closes an issue
- Difficult to test (Not sure how to test Gmail msgs yet)
- Tests will be added later (issue #1409)
> Issue 1392 1393 fix compose screen

- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/bouncycastle/openpgp/PGPKeyRingExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/pgpainless/key/info/KeyRingInfoExt.kt
This PR wrapped KeyRingInfo.getPrimaryKeyExpirationDate() with try/catch to prevent crashes
close #1412
- Tests will be added later (issue #1413)
> Wrapped KeyRingInfo.getPrimaryKeyExpirationDate with a safe call.| #1412

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ImportPgpContactActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ShareIntentsTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/enterprise/CreatePrivateKeyActivityEnterpriseTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/SignInActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/UserRecoverableAuthExceptionFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/notifications/ErrorNotificationManager.kt
- FlowCrypt/src/main/res/navigation/nav_graph.xml
- FlowCrypt/src/main/res/navigation/sing_in_graph.xml
- script/ci-setup-and-run-emulator.sh
This PR fixed a bug in SignInActivity
close #1415
- Difficult to test (explain why) - hard to test sign-in action
> Fixed "SignInActivity does not have a NavController" bug.| #1415

- .github/workflows/check-for-emails.yml
This PR updated check for emails action to FlowCrypt's own fixed version.
original issue arised in another repo: https://github.com/FlowCrypt/flowcrypt-ios/issues/480
Tested on the repo https://github.com/FlowCrypt/issue947-src/
> Update check for emails action

- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpKey.kt
This PR fixed changing passphrase via PGPainless
close #1448
> Fixed changing passphrase via PGPainless.| #1448

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/CreateMessageActivityTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ImportPrivateKeyActivityFromSettingsTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
This PR allowed sha1 for all builds except enterprise
close #1478
> Allowed sha1 for all builds except enterprise.| #1478

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/MessagesSenderWorker.kt
This PR fixed sending a message with atts(reply/reply all)
close #1476
- Difficult to test (I've tested it manually. It should be tested as a flow. We don't support it yet).
> Fixed sending a message with atts(reply/reply all).| #1476

- FlowCrypt/src/main/assets/html/license.htm
This PR added PGPainless ref to licences.html
close #1468
> Added PGPainless ref to licences.html| #1468

- FlowCrypt/src/main/res/xml/network_security_config.xml
This PR allowed the use of user-defined + system SSL certs
close #857
- Difficult to test (explain why). It requires work with System settings. I don't have access to them. Tested manually.
> Allowed use of user-defined + system SSL certs.| #857

- FlowCrypt/src/devTest/res/navigation/nav_graph.xml
- FlowCrypt/src/devTest/res/navigation/sing_in_graph.xml
This PR added a variant of some nav resources for devTest flavour
close #1513
> Added a variant of some nav resources for devTest flavour.| #1513

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/BackupKeysFragmentNoPrvBackupOrgRuleTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/base/AddAccountToDatabaseRuleInterface.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/base/BaseBackupKeysFragmentTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/BackupKeysFragment.kt
This PR added final checking for NO_PRV_BACKUP on the backup screen
close #1512 
> Added final checking for NO_PRV_BACKUP on the backup screen

- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpDecrypt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/FixNeedPassphraseIssueDialogFragment.kt
- FlowCrypt/src/main/res/layout/fragment_fix_empty_passphrase.xml
This PR added using PGPainless to identify missed passphrases for keys that fit
close #1473
> Used PGPainless to identify missed passphrases for keys that fit.| #1473

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/CheckKeysActivity.kt
- FlowCrypt/src/main/res/layout/activity_check_keys.xml
This PR allowed in-memory pass phrase for all build types
close #1567
> Allowed in-memory pass phrase for all build types.| #1567

- FlowCrypt/build.gradle
- FlowCrypt/src/main/AndroidManifest.xml
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/BaseWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/ForwardedAttachmentsDownloaderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/MessagesSenderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/RefreshClientConfigurationWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/BaseSyncWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/SyncInboxWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/SyncInterface.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/EmailManagerActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/LauncherActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/base/BaseActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
This PR added prefetching client configuration depends on conditions
close #1375
- Difficult to test (explain why). This approach uses CoroutineWorker. I have no idea how to test it for now. Tested manually.
> refetch client configuration on every startup

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/JavaEmailConstants.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/MsgsPagedListAdapter.kt
This PR Added more domains to getPublicEmailDomains. 
close #1580
issue #0000 // if it doesn't close the issue yet
> Added more domains to getPublicEmailDomains. Refactored code.| #1580

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
This PR Improved EmailUtil.getDomain()
close #1581
> Improved EmailUtil.getDomain().| #1581

- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/ResultExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/CheckFesServerViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
This PR fixed SSL issue when we are trying to check FES server
close #1565
- Difficult to test (explain why). It's difficult to prepare all the required requirements. Need to have a local webserver with a self-signed cert. Tested manually.
> Fixed SSL issue when we are trying to check FES server.| #1565

- FlowCrypt/src/main/java/com/flowcrypt/email/service/MessagesNotificationManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/PassPhrasesInRAMService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentNotificationManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AddOtherAccountFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/UserRecoverableAuthExceptionFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/notifications/ErrorNotificationManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/notifications/SystemNotificationManager.kt
This PR Added PendingIntent.FLAG_IMMUTABLE to PendingIntent
close #1589
> Added PendingIntent.FLAG_IMMUTABLE to PendingIntent(s).| #1589

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/CreateMessageFragment.kt
This PR fixed a bug of changing availability 'from' addresses
issue #1573
- Difficult to test. It relates to a Gmail account. For now, we can add tests for non-Gmail accounts only. Tested manually.
> Fixed a bug of changing availability 'from' addresses.| #1573

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/MessageDetailsActivityTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/res/layout/fragment_import_recipients_from_source.xml
- FlowCrypt/src/main/res/layout/message_part_public_key.xml
- FlowCrypt/src/main/res/values/strings.xml
- FlowCrypt/src/main/res/values/styles.xml
This PR added warning when manually importing public keys
close #1544
> Issue 1544 add warning when manually importing public keys

- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpEncryptAndOrSign.kt
This PR Fixed sending encrypted attachments
close #1630
- Tests will be added later (issue #1631 )
> Fixed sending encrypted attachments.| #1630

- FlowCrypt/src/main/res/values/preferences.xml
- FlowCrypt/src/main/res/values/strings.xml
- FlowCrypt/src/main/res/values/strings_dev_settings.xml
This PR marked some strings as translatable="false"
close #1637
> Marked some strings as translatable="false".| #1637

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt
This PR fixed sending web portal message so that it can be replied online.
close #1636
issue #0000 // if it doesn't close the issue yet
> Fixed sending web portal message so that it can be replied online.

- FlowCrypt/src/main/res/layout/activity_check_keys.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
- FlowCrypt/src/main/res/values/strings_dev_settings.xml
This PR fixed lint warnings after adding Russian translation
close #1545
> Fixed lint warnings after adding Russian translation.| #1645

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/ForwardedAttachmentsDownloaderWorker.kt
This PR Fixed sending forwarded attachments with attached
close #1647
- Tests will be added later (issue #1631)
> Fixed sending forwarded attachments with attached.| #1647

- FlowCrypt/src/consumer/java/com/flowcrypt/email/util/FlavorSettings.kt
- FlowCrypt/src/dev/java/com/flowcrypt/email/util/FlavorSettings.kt
- FlowCrypt/src/devTest/java/com/flowcrypt/email/util/FlavorSettings.kt
- FlowCrypt/src/enterprise/java/com/flowcrypt/email/util/FlavorSettings.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/MainDevPreferencesFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/EnvironmentSettings.kt
- FlowCrypt/src/main/res/values/strings_dev_settings.xml
- FlowCrypt/src/main/res/xml/dev_preferences.xml
- ext.gradle
This PR modified leakcanary configuration
close #1657
> Modified leakcanary configuration.| #1657

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
This PR fixed issues for enterprise users.
close #1713
- Tests will be added later (issue #1631 )
> Issue 1713 fix sending msgs

- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/javax/mail/internet/MimeMessageExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt
This PR fixed sending password-protected messages
close #1731
- Difficult to test (explain why). It uses Gmail API. Tested manually.
> Fixed sending password-protected messages.| #1731

- FlowCrypt/build.gradle
- build.gradle
- ext.gradle
This PR Updated `build.gradle` to support `dependabot`
close #1776 
> Update build.gradle to support dependabot

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/base/BaseTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenImportRecipientPubKeyFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/ImportMissingPublicKeyFragmentInIsolationTest.kt
- FlowCrypt/src/devTest/res/navigation/nav_graph.xml
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/FragmentExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/LifecycleOwnerExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/EditContactFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ImportAdditionalPrivateKeysFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ImportMissingPublicKeyFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ImportPrivateKeysDuringSetupFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ImportRecipientsFromSourceFragment.kt
- FlowCrypt/src/main/res/navigation/create_msg_graph.xml
- FlowCrypt/src/main/res/navigation/find_keys_in_clipboard_dialog_graph.xml
- FlowCrypt/src/main/res/navigation/nav_graph.xml
- FlowCrypt/src/main/res/navigation/parse_keys_from_source_dialog_graph.xml
This PR fixed some navigation issues
close #1799 
> Fixed navigation issues in ImportMissingPublicKeyFragment

- .github/workflows/add-opened-issue-to-project.yml
This PR Added ability to automatically add the current issue a GitHub project
close #1803
> Added ability to automatically add the current issue a GitHub project

- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/LabelDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/MessageDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/RecipientDao.kt
This PR refcatored code.
close #1574
> Refactored code.| #1574

- FlowCrypt/src/androidTest/assets/messages/info/standard_msg_info_plaintext_outbox.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
This PR fixed "Outbox not found" issue
close #1834
> Issue 1834 fix outbox bug

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/FragmentExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/BackupKeysFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PrivateKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/UserRecoverableAuthExceptionFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/ChoosePublicKeyDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/NoPgpFoundDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/MainDevPreferencesFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/activity/result/contract/CustomActivityResultContracts.kt
- FlowCrypt/src/main/res/navigation/choose_public_key_dialog_graph.xml
- FlowCrypt/src/main/res/navigation/create_msg_graph.xml
- FlowCrypt/src/main/res/navigation/nav_graph.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR drooped onActivityResult as deprecated
close #1829
> Issue 1829 drop on activity result

- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/androidx/navigation/NavControllerExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AuthorizeAndSearchBackupsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CheckKeysFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateOrImportPrivateKeyDuringSetupFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ImportAdditionalPrivateKeysFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ImportPrivateKeysDuringSetupFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/FixNeedPassphraseIssueDialogFragment.kt
This PR fixed some navigation issues
close #1835, close #1839
> Fix navigation issues

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/LegalSettingsFragmentInIsolationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/androidx/viewpager2/widget/ViewPager2Ext.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/LegalSettingsFragment.kt
- FlowCrypt/src/main/res/layout/fragment_legal.xml
This PR added migration from ViewPager to ViewPager2
close #1851
> Migrated from ViewPager to ViewPager2.| #1851

- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR updated strings
close #1861
> Updated strings.| #1861

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
This PR fixed NPE in MessagesListFragment
close #1837
> Fixed NPE in MessagesListFragment.| #1837

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/FeedbackFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PrivateKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PublicKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/SelectRecipientsFragment.kt
This PR fixed issues with MenuProvider
close #1887
> Fixed issues with MenuProvider

- FlowCrypt/src/main/res/drawable/selector_msg_item.xml
- FlowCrypt/src/main/res/drawable/shape_control_highlight.xml
- FlowCrypt/src/main/res/layout/key_item.xml
- FlowCrypt/src/main/res/layout/messages_list_item.xml
- FlowCrypt/src/main/res/layout/public_key_item.xml
This PR fixed the message selector bug for Android 9 and less
close #1902
> Fixed the message selector bug for Android 9 and less.| #1902

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BaseFragment.kt
- FlowCrypt/src/main/res/layout/fragment_create_message.xml
This PR Fixed day/night bug on some screens
close #1905 
> Fix day/night bug on some screens

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ImportAdditionalPrivateKeysFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ImportAdditionalPrivateKeysFragment.kt
This PR fixed a bug in ImportAdditionalPrivateKeysFragment.
close #1922
> Fixed a bug in ImportAdditionalPrivateKeysFragment.| #1922

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/rules/CustomScreenCaptureProcessor.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/base/BasePassphraseActivityTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/FoldersManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/wkd/WkdClient.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/MessageDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/CheckEmailSettingsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/RecipientsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/ArchiveMsgsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/DeleteMessagesPermanentlyWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/DeleteMessagesWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/MovingToInboxWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/UpdateMsgsSeenStateWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AddOtherAccountFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/UserRecoverableAuthExceptionFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BasePassphraseStrengthFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
This PR fixed lowercase() and uppercase() usage
close #1434 
> Migrated to use lowercase() and uppercase() over the whole project.

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/AccountPublicKeyServersViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AttesterSettingsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/AttesterKeyAdapter.kt
This PR fixed the identity issue in AttesterSettingsFragment
close #1313
- Difficult to test (explain why). It relates to Gmail accounts. Tested manually.
> Fixed identity issue in AttesterSettingsFragment.| #1313

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/UserRecoverableAuthExceptionFragmentInIsolationTest.kt
- FlowCrypt/src/main/res/layout/fragment_user_recoverable_auth_exception.xml
This PR fixed an issue in UserRecoverableAuthExceptionFragment
close #1932 
> Issue 1932 fix issue you must supply a layout width attribute

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/base/BaseTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CheckKeysFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateOrImportPrivateKeyDuringSetupFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreatePrivateKeyFirstFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreatePrivateKeySecondFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/FeedbackFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ProvidePasswordToProtectMsgFragment.kt
- FlowCrypt/src/main/res/layout/fragment_check_keys.xml
- FlowCrypt/src/main/res/layout/fragment_check_passphrase_strength.xml
- FlowCrypt/src/main/res/layout/fragment_create_or_import_private_key_during_setup.xml
- FlowCrypt/src/main/res/layout/fragment_create_private_key_first.xml
- FlowCrypt/src/main/res/layout/fragment_create_private_key_second.xml
- FlowCrypt/src/main/res/layout/fragment_feedback.xml
- FlowCrypt/src/main/res/layout/fragment_provide_password_to_protect_msg.xml
- FlowCrypt/src/main/res/layout/fragment_recheck_provided_passphrase.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR refactored code.
close #1896
> Used Flowcrypt as link in strings.| #1896

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AddOtherAccountFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/UserRecoverableAuthExceptionFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BaseOAuthFragment.kt
This PR fixed Outlook sign-in
close #1810
- Difficult to test (explain why). It requires a real Outlook account to make a test. Tested manually.
> Fixed Outlook sign-in.| #1810

- FlowCrypt/schemas/com.flowcrypt.email.database.FlowCryptRoomDatabase/32.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/database/MigrationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/RecipientDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/KeyEntity.kt
This PR fixed some Android Room warnings.
close #1945 
> Issue 1945 fix room warnings

- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/api/PostHelpFeedbackResponse.kt
This PR fixed PostHelpFeedbackResponse
close #1941 
> Fixed PostHelpFeedbackResponse

- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/attester/TestWelcomeResponse.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
This PR added using response code when checking welcome message "sent" status
close #1961
> Migrated to use response code when checking welcome message "sent" status

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseRefreshKeysFromEkmFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PrivateKeyDetailsFragmentPassInRamFlexibleTimeInIsolationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/OrgRules.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PgpKeyDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/KeysStorageImpl.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/PassPhrasesInRAMService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PrivateKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/FixNeedPassphraseIssueDialogFragment.kt
This PR added flexible pass phrase session
close #1962
> Issue 1962 flexible pass phrase session

- FlowCrypt/src/main/java/com/flowcrypt/email/api/wkd/WkdClient.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/BetterEmailAddress.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/util/BetterInternetAddressTest.kt
This PR fixed fetching pubkeys from WKD.
close #1953 
> Fixed fetching pubkeys from WKD. Updated tests.| #1953

- .github/CODEOWNERS
This PR updates CODEOWNERS file so that reviews are requested from @ioanmo226 instead of @IvanPizhenko 
no issue
**Tests**:
> updated codeowners file

- FlowCrypt/src/main/java/com/flowcrypt/email/service/actionqueue/actions/Action.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/google/gson/ActionJsonDeserializer.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/util/google/gson/ActionJsonDeserializerTest.kt
This PR fixed no enum bug
close #2019
> Fixed no enum bug.| #2019

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/PublicKeyDetailsHideArmorMetaFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/bouncycastle/openpgp/PGPKeyRingExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/bouncycastle/openpgp/PGPPublicKeyExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/CreatePrivateKeyViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/DraftViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/KeysWithEmptyPassphraseViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PgpKeyDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PublicKeyDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/SecurityUtils.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpEncryptAndOrSign.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpKey.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/ProcessingOutgoingMessageInfoHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/actionqueue/actions/BackupPrivateKeyToInboxAction.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PublicKeyDetailsFragment.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpEncryptAndOrSignTest.kt
This PR added support for HIDE_ARMOR_META flag
close #1532
> Issue 1532 hide armor meta

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenDraftGmailAPIFlowTest.kt
- FlowCrypt/src/devTest/java/com/flowcrypt/email/util/FlavorSettings.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/EnvironmentSettings.kt
This PR added tests for saving drafts via Gmail API
close #2004 
> Issue 2004 gmail mock api

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
This PR fixed NPE in GmailApiHelper.generateGmailApiService()
close #2072
> Fixed NPE in GmailApiHelper.generateGmailApiService().| #2072

- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/android/webkit/WebViewExt.kt
This PR fixed day/night UI issue
close #2026
> Fixed day/night UI issue

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/rules/AddGmailAliasToDatabaseRule.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/CreateMessageTestRecipientsDuringReplyAllFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/CreateMessageFragmentRecipientsDuringReplyAllInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/LegalSettingsFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PrivateKeysListFragmentEkmInIsolationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/IncomingMessageInfo.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
This PR made code refactoring and added a few tests.
close #2002
> Tests for recipient for REPLY_ALL case. Refactored code.

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/SubmitPublicKeyToAttesterForImportedKeyDuringSetupFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/AddOtherAccountFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BaseSingInFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/ParsePgpKeysFromSourceDialogFragment.kt
This PR Fixed submitting pub key when setting up with imported key
close #2014
> Issue 2014 submitting pub key when setting up with imported key

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/base/BaseTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/junit/filters/OtherTestsFilter.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/matchers/DrawableMatcher.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/matchers/EmptyListViewMather.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/matchers/EmptyRecyclerViewMatcher.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/matchers/RecyclerViewItemCountMatcher.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/matchers/SecurityTypeOptionMatcher.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/rules/AddLabelsToDatabaseRule.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/rules/RepeatedRule.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/security/KeyStoreCryptoManagerTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseBackupKeysFragmentTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseMessageDetailsFlowTest.kt
This PR refactored and simplified some code
issue #2005
> Internal improvements

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/FoldersManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/UpdateLabelsWorker.kt
- FlowCrypt/src/main/res/layout/activity_main.xml
- FlowCrypt/src/main/res/values/styles.xml
This PR fixed hierarchy of Gmail labels
close #2112
> Fixed hierarchy of Gmail labels.| #2112

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/rules/AddPrivateKeyToDatabaseRule.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/PublicKeyDetailsFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PrivateKeyDetailsFragmentExpiredKeyInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PrivateKeyDetailsFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PrivateKeysListFragmentInIsolationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PrivateKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PublicKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/UpdateRecipientPublicKeyDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/PrivateKeysRecyclerViewAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/PubKeysRecyclerViewAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/DateTimeUtil.kt
This PR fixed the timezone difference for 'key expiration'.
close #2121
issue #0000 // if it doesn't close the issue yet
> Fixed timezone difference for 'key expiration'.| #2121

- .semaphore/semaphore.yml
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MainSignInFragmentEnterpriseFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/DomainOrgRulesViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
- script/ci-setup-and-run-emulator.sh
- script/ci-wait-for-emulator.sh
This PR Fixed a bug in DomainOrgRulesViewModel
close #2136
> Fixed a bug in DomainOrgRulesViewModel

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MainSignInFragmentEnterpriseFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
This PR Added support for FES 2023-01
close #2142
> Issue 2142 Add support for FES 2023-01

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/javamail/ForwardedAttachmentInfoDataSource.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpEncryptAndOrSign.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/ProcessingOutgoingMessageInfoHelper.kt
This PR fixed the wrong names for file encryption
close #2179 
> Issue 2179 fix wrong names for file encryption

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
This PR fixed a small bug in MessagesListFragment(Action Mode usage). + Improved [SendMsgTest](it failed sometimes)
close #2213
> Fixed a small bug in MessagesListFragment

- FlowCrypt/build.gradle
- FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/MainDevPreferencesFragment.kt
This PR Disabled running ACRA for enterprise builds
close #2174
> Disabled running ACRA for enterprise builds.| #2174

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/UseFesAfterSetupDuringRefreshingClientConfigurationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/ApiClientRepository.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/RefreshClientConfigurationWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
This PR resolved "call fes.domain.com first before falling back on flowcrypt.com/shared-tenant-fes"
close #2237 
> Modified FES usage logic

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MainSignInFragmentFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/RefreshClientConfigurationWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR Added fetching client configuration for public domains
close #2226 
> Added fetching client configuration for public domains

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/junit/filters/ReadyForCIFilter.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/rules/RetryRule.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/LegalSettingsFragmentInIsolationTest.kt
This PR Increased attempts count for flaky tests
close #2219
> Increased attempts count for flaky tests

- .github/dependabot.yml
This PR Updated `dependabot` to do weekly updates
close #2223
> Updated dependabot.yml.| #2223

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsPassphraseInRamFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/AttesterSettingsFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/EndPassPhraseSessionInIsolationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PgpKeyDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/model/KeysStorage.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/KeysStorageImpl.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/PassPhrasesInRAMService.kt
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR Added ability to end pass phrase session from the notification bar
close #2228
> end pass phrase session from the notification bar

- .idea/codeStyles/Project.xml
- .idea/runConfigurations/Run_JUnit_Tests.xml
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/SendPasswordProtectedMessageFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt
This PR fixed hiding BCC
close #2279
> Issue 2279 blind carbon copy

- FlowCrypt/build.gradle
- script/prod-release.sh
This PR Fixed 'copyReleaseApks' task usage.
close #2288
> Fixed 'copyReleaseApks' task usage.

- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/api/ClientConfigurationResponse.kt
This PR Removed unused code
close #2289
> Remove ["domain_org_rules"]

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsEkmFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/AccountEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentNotificationManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/DownloadAttachmentTaskResult.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/DownloadAttachmentDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/AttachmentsRecyclerViewAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/PubKeysArrayAdapter.kt
This PR allowed previewing of attachments for all.
close #2137
> Issue 2137 preview attachments for all

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MessagesViewModel.kt
This PR Fixed NPE errors. Refactored code
close #2319
> Fixed NPE errors. Refactored code

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenExternalIntentsFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/AttachmentInfoExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/AttachmentsRecyclerViewAdapter.kt
- FlowCrypt/src/main/res/layout/attachment_item.xml
- FlowCrypt/src/main/res/layout/fragment_create_message.xml
This PR improved user experience - previewing attachment on the compose screen
close #1394
> click on attachment in compose box to download it back

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenNoSuitablePrivateKeysFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/InfoDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
This PR Improved error details for keys on compose screen
close #1292
> Improve error details for keys on compose screen

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ImportUpdatedVersionOfPrivateKeyViaSettingsImportFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CheckKeysFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/ImportAdditionalPrivateKeysFragment.kt
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR Allowed ONLY IMPORT from 'Settings -> Keys -> Import'
close #2337 
issue #0000 // if it doesn't close the issue yet
> Allowed ONLY IMPORT from 'Settings -> Keys -> Import'

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenReloadPublicKeyFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ComposeMsgViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BaseFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/NoPgpFoundDialogFragment.kt
- FlowCrypt/src/main/res/drawable/ic_refresh_gray_48.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR Added the ability to reload failed pubkey search
close #476 
> Added ability to reload failed pubkey search

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseMessageDetailsFlowTest.kt
This PR Added a test for quotes ("reply/reply all")
close #885
> Added a test for quotes ("reply/reply all")

- FlowCrypt/build.gradle.kts
This PR completed migration to Kotlin DSL
close #2409
> Complete migration to Kotlin DSL

- FlowCrypt/build.gradle.kts
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/com/sun/mail/imap/IMAPFolderExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/BackupsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/LoadPrivateKeysViewModel.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/api/email/EmailUtilTest.kt
This PR Added ignoring Sent and Trash folders when searching backups
close #1651 
> Added ignoring Sent and Trash folders when searching backups

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/api/email/EmailUtilTest.kt
This PR Fixed backups search for Gmail API 
close #1651
> Fixed backups search for Gmail API.| #1651

- FlowCrypt/src/androidTest/assets/messages/info/open_pgp_mime_with_inlined_attachments.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/jakarta/mail/MultipartExt.kt
This PR Improved handling PGP/MIME
close #2402 
> Improved handling PGP/MIME

- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/AttachmentDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
This PR Fixed showing inlined attachments
close #2429
> Fixed showing inlined attachments.| #2429

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/protocol/ImapProtocolUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/jakarta/mail/PartExt.kt
This PR Fixed a bug of recognizing attachments things
close #2425
> Fixed a bug of recognizing attachments things

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/BaseActivity.kt
This PR Added ability to hide app content when app is in background
close #2442
> Added ability to hide app content when app is in background

- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
This PR Fixed a style for the dark mode
close #2075
> Fixed a style for the dark mode

- FlowCrypt/schemas/com.flowcrypt.email.database.FlowCryptRoomDatabase/39.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/database/MigrationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/FoldersManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/LocalFolder.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/LabelDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/LabelEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/UpdateLabelsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/res/drawable/ic_bug_report_grey_32dp.xml
- FlowCrypt/src/main/res/drawable/ic_exit_to_app_grey_32dp.xml
- FlowCrypt/src/main/res/drawable/ic_settings_grey_32dp.xml
- FlowCrypt/src/main/res/layout/activity_main.xml
This PR improved displaying Gmail labels
close #2448 
> improved displaying gmail labels

- FlowCrypt/schemas/com.flowcrypt.email.database.FlowCryptRoomDatabase/40.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/database/MigrationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/MessageEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/kotlin/StringExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/DownloadAttachmentViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/ForwardedAttachmentsDownloaderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/UploadDraftsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/GmailApiLabelsListAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/MsgsPagedListAdapter.kt
- FlowCrypt/src/main/res/layout/fragment_message_details.xml
- FlowCrypt/src/main/res/layout/item_label_badge.xml
- FlowCrypt/src/main/res/layout/messages_list_item.xml
This PR Added displaying Gmail labels in the message list and on the message details screen. Part of #2020 
issue #2020
> Added displaying Gmail labels in the message list and on the message details screen

- FlowCrypt/schemas/com.flowcrypt.email.database.FlowCryptRoomDatabase/40.json
- FlowCrypt/src/androidTest/assets/messages/info/standard_msg_reply_all_via_gmail_alias.json
- FlowCrypt/src/androidTest/assets/messages/info/standard_msg_reply_to_header.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/DraftsGmailAPITestCorrectSendingFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/FoldersManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/LocalFolder.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/converters/LabelListVisibilityConverter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/LabelDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/LabelEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/UpdateLabelsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
This PR Added "label_list_visibility" to "labels" table
issue #2020 
> Added "label_list_visibility" to "labels" table

- FlowCrypt/schemas/com.flowcrypt.email.database.FlowCryptRoomDatabase/41.json
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/database/MigrationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptRoomDatabase.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/MessageDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/MessageEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/ViewExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/GmailLabelsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MessagesViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/InboxIdleSyncWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/model/LabelWithChoice.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/ProgressBehaviour.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/ChangeGmailLabelsForSingleMessageDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/GmailApiLabelsListAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/GmailApiLabelsWithChoiceListAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/MsgsPagedListAdapter.kt
- FlowCrypt/src/main/res/layout/fragment_change_gmail_labels_for_single_message.xml
- FlowCrypt/src/main/res/layout/fragment_message_details.xml
- FlowCrypt/src/main/res/layout/item_gmail_label_with_checkbox.xml
- FlowCrypt/src/main/res/layout/status.xml
- FlowCrypt/src/main/res/menu/fragment_message_details.xml
- FlowCrypt/src/main/res/navigation/nav_graph.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/dimens.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR added the ability to change message labels
issue #2020
- Tests will be added later (issue #2464)
> Issue 2020 change labels on message details screen

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/FoldersManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/AccountEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/MessageEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/kotlin/StringExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/DraftViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/GmailLabelsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/LabelsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/base/BaseMoveMessagesWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/ArchiveMsgsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/MarkAsNotSpamWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/MovingToInboxWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/MovingToSpamWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/UpdateLabelsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
- FlowCrypt/src/main/res/layout/fragment_message_details.xml
- FlowCrypt/src/main/res/menu/fragment_message_details.xml
- FlowCrypt/src/main/res/menu/message_list_context_menu.xml
This PR improved the accessibility of archived email 
close #2398
- Tests will be added later #2470 
> imrove accessibility of archived email 

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/selection/CustomStableIdKeyProvider.kt
This PR improved swiping, scrolling, and using the selection track on the message list screen.
close #2468
> Issue 2468 imrove scroll and swipe

- FlowCrypt/build.gradle.kts
- build.gradle.kts
This PR Added using GIT for the app version name for debug builds
close #191
> Added using GIT for the app version name for debug builds

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/matchers/CustomMatchers.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/RecipientDetailsFragmentInIsolationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/model/PgpKeyRingDetails.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/PrivateKeyDetailsFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/PrivateKeysRecyclerViewAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/PubKeysRecyclerViewAdapter.kt
- FlowCrypt/src/main/res/layout/fragment_recipient_details.xml
This PR Added RecipientDetailsFragmentInIsolationTest
close #2490
> Added RecipientDetailsFragmentInIsolationTest

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/bouncycastle/openpgp/PGPKeyRingExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/bouncycastle/openpgp/PGPPublicKeyExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/org/bouncycastle/openpgp/PGPPublicKeyRingCollectionExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/SecurityUtils.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpArmor.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/BaseUpdateKeyDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/dialog/BaseDialogFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/model/NavigationViewManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
- build.gradle.kts
This PR fixed some lint warnings
close #2515
> fixed some lint warnings

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt
This PR Improved running additional actions after the private key creation
close #2514
> Improved running additional actions after the private key creation

- .github/CODEOWNERS
This PR changed owner to Sosnovsky
> Changed owner to Sosnovsky

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/RefreshPrivateKeysFromEkmViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/RefreshClientConfigurationWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/google/GoogleApiClientHelper.kt
This PR Fixed using a wrong Google JWT token for APIs
close #2528
> Fixed using a wrong Google JWT token for APIs

- FlowCrypt/src/androidTest/assets/messages/info/cryptup_reply_div_should_be_hidden_in_FES_messages.json
- FlowCrypt/src/androidTest/assets/messages/mime/cryptup_reply_div_should_be_hidden_in_FES_messages.txt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessageDetailsFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt
This PR hides `cryptup_reply` div in FES messages
close #2536 
> cryptup_reply div should be hidden in FES messages

- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/AttachmentInfo.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/AttMsgBlock.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/AttachmentInfoExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/jakarta/mail/PartExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/AttachmentsRecyclerViewAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/adapter/FromAddressesAdapter.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/FileAndDirectoryUtils.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/util/CreateFileWithIncreasedIndexTest.kt
This PR improved handling attachments
close #2538
> improve handling attachments

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/rules/AddAccountToDatabaseRule.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/IMAPStoreManager.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/AccountEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/AccountViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/DownloadAttachmentViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/ForwardedAttachmentsDownloaderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/MessagesSenderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/BaseSyncWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/IdleService.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/ProcessingOutgoingMessageInfoHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/actionqueue/actions/BackupPrivateKeyToInboxAction.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.kt
This PR Fixed sending messages(reply/reply all)
close #2545
- Tests will be added later (issue #1821 will contain a lot of changes that relate to message sending. Tests will be updated there.)
> Fixed sending messages(reply/reply all)

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseMessageDetailsFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BasePublicKeyDetailsTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/CreatePrivateKeySecondFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/EditContactFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/ImportPrivateKeysDuringSetupFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/ImportRecipientsFromSourceFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/MainSignInFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/MessageDetailsFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/MessagesListFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/NotificationsSettingsFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PrivateToPublicKeyDetailsFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/PublicKeyDetailsInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/SearchBackupsInEmailFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/ServerSettingsFragmentInIsolationTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fragment/isolation/incontainer/UpdatePrivateKeyFragmentInIsolationTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/NotificationsSettingsFragment.kt
This PR Added a few 'in isolation' tests
close #1746 
> Added a few 'in isolation' tests

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/UpdatePrivateKeyWithPassPhraseInDatabaseFlowTest.kt
- FlowCrypt/src/main/AndroidManifest.xml
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/MessagesSenderWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/service/PassPhrasesInRAMService.kt
This PR Added using foreground service type(required in Android 14 and high)
close #2625 
> Added using foreground service type

- FlowCrypt/build.gradle.kts
- FlowCrypt/src/main/AndroidManifest.xml
- FlowCrypt/src/main/java/com/flowcrypt/email/database/FlowCryptMigration.kt
- build.gradle.kts
- script/prod-release.sh
This PR added changes to prevent making releases using non-master branches + updated some libs + refactored code
close #2638
> Issue 2638 prevent releases for non master branch

- script/ci-instrumentation-tests-enterprise.sh
- script/ci-instrumentation-tests-with-mailserver.sh
- script/ci-instrumentation-tests-without-mailserver.sh
This PR Added '--info' when run instrumentation tests for better debugging
issue #2649 
> Added '--info' when run instrumentation tests.| #2649

- FlowCrypt/src/main/AndroidManifest.xml
- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
This PR reverted back a custom configuration for WorkManager to prevent unexpected bugs.
close #2657
> Reverted back a custom configuration for WorkManager to prevent unexpected bugs

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseComposeGmailFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedForwardOfEncryptedMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedForwardOfStandardMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedReplyAllComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedReplyComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardForwardOfEncryptedMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardForwardOfEncryptedPgpMimeMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardForwardOfStandardMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardReplyAllComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardReplyComposeGmailApiFlow.kt
This PR includes code refactoring
close #2681
> code refactoring

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/ComposeScreenNoKeyAvailableSingleKeyWithPassphraseInRamFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseComposeGmailFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseGmailApiTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedForwardOfEncryptedMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedForwardOfStandardMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedReplyAllComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedReplyComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedWithAttachmentsAndOwnPublicKeyComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/EncryptedWithAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/PasswordProtectedEncryptedComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/SearchMessagesGmailApiFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardForwardOfEncryptedMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardForwardOfEncryptedPgpMimeMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardForwardOfStandardMessageWithOriginalAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardReplyAllComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardReplyComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardWithAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardWithPublicKeyComposeGmailApiFlow.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MessagesViewPagerViewModel.kt
This PR Fixed bug "Wrong message is loaded from search results"
close #2692
- Difficult to test (explain why)
- Not worth testing
- Tests will be added later (issue #...)
> Fixed bug "Wrong message is loaded from search results"

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/DraftsGmailAPITestCorrectSendingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/MessagesListChangeGmailLabelsFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseComposeGmailFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseComposeScreenTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardReplyComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/gmailapi/StandardWithAttachmentsComposeGmailApiFlow.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/viewaction/CustomViewActions.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/viewaction/WaitUntilGoneAction.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/viewaction/WaitUntilTextGoneAction.kt
This PR fixed some flaky tests
issue #2642
> Fixed some flaky tests

- FlowCrypt/src/main/res/layout/nav_header.xml
This PR fixed the missed avatar image
close #2741 
> fixed missed avatar image

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
This PR fixed some NPE
close #2775
close #2776
> Fixed some NPE 

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/EmailAndNameWorker.kt
This PR Improved EmailAndNameWorker
close #2774
> Improved EmailAndNameWorker enqueuing.| #2774

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/DraftsGmailAPITestCorrectCreatingAndUpdatingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/DraftsGmailAPITestCorrectDeletingFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/RecipientsListFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseDraftsGmailAPIFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/FlowCryptApplication.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailApiHelper.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/MessageDao.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/MessageEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/AccountViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MessagesViewModel.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/BaseIdleWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/InboxIdleSyncWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/SyncDraftsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessagesListFragment.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/preferences/NotificationsSettingsFragment.kt
- FlowCrypt/src/main/res/drawable/ic_security_32.xml
- FlowCrypt/src/main/res/layout/action_item_switch.xml
- FlowCrypt/src/main/res/menu/fragment_messages_list.xml
- FlowCrypt/src/main/res/menu/side_menu.xml
- FlowCrypt/src/main/res/values-ru/strings.xml
- FlowCrypt/src/main/res/values-uk/strings.xml
- FlowCrypt/src/main/res/values/ids.xml
- FlowCrypt/src/main/res/values/strings.xml
This PR Added option 'Load only PGP messages'
close #1907 
- Difficult to test (explain why): To test switching `Load only PGP messages` mode we need to have at least one of every PGP message case. It will take a lot of time to create such testing requirements. Tested manually.
> Added option 'Load only PGP messages'

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/base/BaseTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/AttachmentDownloadingWithRestrictionFlowTest.kt
- FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/EndPassPhraseSessionFlowTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt
- FlowCrypt/src/main/res/layout/status.xml
This PR Fixed downloading attachments
close #2806
> Fixed downloading attachments

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MainActivity.kt
- FlowCrypt/src/main/res/layout/action_item_switch.xml
This PR Improved UI for switch
close #2805 
> Improved UI for switch

- FlowCrypt/src/androidTest/java/com/flowcrypt/email/GeneralTest.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/MessageEntity.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/extensions/kotlin/StringExt.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/sync/LoadRecipientsWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/KeysStorageImpl.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/security/model/PgpKeyRingDetails.kt
This PR Improved parsing InternetAddress
close #2819 
> Improved parsing InternetAddress

- FlowCrypt/src/main/java/com/flowcrypt/email/providers/EmbeddedAttachmentsProvider.kt
This PR Improved EmbeddedAttachmentsProvider
close #2824
> Improved EmbeddedAttachmentsProvider

- FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/CreateMessageFragment.kt
This PR Fixed a small bug in CreateMessageFragment
close #2921
> Fixed Gmail signature usage when composing new message

- FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailHistoryHandler.kt
This PR Refactored code
close #3003 
> Refactored code

- FlowCrypt/src/main/java/com/flowcrypt/email/database/entity/MessageEntity.kt
- FlowCrypt/src/test/java/com/flowcrypt/email/database/entity/MessageEntityTest.kt
This PR Sorted labels to show INBOX first
close #3002 
> Sort labels to show INBOX first.| #3002

- FlowCrypt/build.gradle.kts
This PR Fixed gradle 'copyReleaseApks' task
close #3038
> Fixed gradle 'copyReleaseApks' task.| #3038

- FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/EmailAndNameWorker.kt
- FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt
This PR Fixed NPE in EmailAndNameWorker
close #3040
> Fixed NPE in EmailAndNameWorker

- ext.gradle.kts
This PR Updated compileSdkVersion and targetSdkVersion to 36
close #3085 
> Updated compileSdkVersion and targetSdkVersion to 36

- .github/CODEOWNERS
This PR Updated .github/CODEOWNERS
close #3088 
> Updated .github/CODEOWNERS
